{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "32cf6be6-d737-4477-8541-b73d40123744",
   "metadata": {},
   "source": [
    "## Research Methods - Final Project\n",
    "\n",
    "ESSEC Master in Finance - Due December 31st, 2025\n",
    "\n",
    "\n",
    "Valentin Catteau - Edouard Decourcelle - Aymeric Laurioz - Saad Waqar"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "75e39ae1-9626-4f23-933b-f1dc833d92d9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import statsmodels.api as sm\n",
    "import statsmodels.formula.api as smf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "738ba1a5-4569-4d35-b7e4-abf8f040ad13",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>Unnamed: 1</th>\n",
       "      <th>Unnamed: 2</th>\n",
       "      <th>Unnamed: 3</th>\n",
       "      <th>Unnamed: 4</th>\n",
       "      <th>NYSE:IBM</th>\n",
       "      <th>Currency</th>\n",
       "      <th>USD</th>\n",
       "      <th>Date</th>\n",
       "      <th>45292</th>\n",
       "      <th>...</th>\n",
       "      <th>Unnamed: 30</th>\n",
       "      <th>Unnamed: 31</th>\n",
       "      <th>Unnamed: 32</th>\n",
       "      <th>Unnamed: 33</th>\n",
       "      <th>Unnamed: 34</th>\n",
       "      <th>Unnamed: 35</th>\n",
       "      <th>Unnamed: 36</th>\n",
       "      <th>Unnamed: 37</th>\n",
       "      <th>Unnamed: 38</th>\n",
       "      <th>Unnamed: 39</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1000</td>\n",
       "      <td>2000</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>INTERNATIONAL BUSINESS MACHINES CORPORATION</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>(in millions of USD)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Key Financials ¹\\nFor the Fiscal Period Ending...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Ticker</td>\n",
       "      <td>Buyers/Investors</td>\n",
       "      <td>Transaction Ticker</td>\n",
       "      <td>Total Transaction Value ($USDmm, Historical rate)</td>\n",
       "      <td>Company Type [Target/Issuer]</td>\n",
       "      <td>NOSH</td>\n",
       "      <td>EBITDA</td>\n",
       "      <td>EBITDA Margin</td>\n",
       "      <td>Total Assets</td>\n",
       "      <td>Book Value Equity</td>\n",
       "      <td>...</td>\n",
       "      <td>Share Price D+4</td>\n",
       "      <td>Consideration Offered</td>\n",
       "      <td>Total Cash ($USDmm, Historical rate)</td>\n",
       "      <td>Cash % of Consideration (%)</td>\n",
       "      <td>Total Debt ($USDmm, Historical rate)</td>\n",
       "      <td>Debt % of Consideration (%)</td>\n",
       "      <td>Stock % of Consideration (%)</td>\n",
       "      <td>Buyer's Headquarter</td>\n",
       "      <td>Seller's Headquarter</td>\n",
       "      <td>Beta</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 40 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                          Unnamed: 0        Unnamed: 1  \\\n",
       "0                                                NaN               NaN   \n",
       "1        INTERNATIONAL BUSINESS MACHINES CORPORATION               NaN   \n",
       "2                               (in millions of USD)               NaN   \n",
       "3  Key Financials ¹\\nFor the Fiscal Period Ending...               NaN   \n",
       "4                                            Ticker   Buyers/Investors   \n",
       "\n",
       "            Unnamed: 2                                         Unnamed: 3  \\\n",
       "0                  NaN                                                NaN   \n",
       "1                  NaN                                                NaN   \n",
       "2                  NaN                                                NaN   \n",
       "3                  NaN                                                NaN   \n",
       "4  Transaction Ticker   Total Transaction Value ($USDmm, Historical rate)   \n",
       "\n",
       "                     Unnamed: 4 NYSE:IBM Currency            USD  \\\n",
       "0                           NaN      NaN      NaN            NaN   \n",
       "1                           NaN      NaN      NaN            NaN   \n",
       "2                           NaN      NaN      NaN            NaN   \n",
       "3                           NaN      NaN      NaN            NaN   \n",
       "4  Company Type [Target/Issuer]     NOSH   EBITDA  EBITDA Margin   \n",
       "\n",
       "           Date              45292  ...      Unnamed: 30  \\\n",
       "0          1000               2000  ...              NaN   \n",
       "1           NaN                NaN  ...              NaN   \n",
       "2           NaN                NaN  ...              NaN   \n",
       "3           NaN                NaN  ...              NaN   \n",
       "4  Total Assets  Book Value Equity  ...  Share Price D+4   \n",
       "\n",
       "             Unnamed: 31                           Unnamed: 32  \\\n",
       "0                    NaN                                   NaN   \n",
       "1                    NaN                                   NaN   \n",
       "2                    NaN                                   NaN   \n",
       "3                    NaN                                   NaN   \n",
       "4  Consideration Offered  Total Cash ($USDmm, Historical rate)   \n",
       "\n",
       "                   Unnamed: 33                           Unnamed: 34  \\\n",
       "0                          NaN                                   NaN   \n",
       "1                          NaN                                   NaN   \n",
       "2                          NaN                                   NaN   \n",
       "3                          NaN                                   NaN   \n",
       "4  Cash % of Consideration (%)  Total Debt ($USDmm, Historical rate)   \n",
       "\n",
       "                   Unnamed: 35                   Unnamed: 36  \\\n",
       "0                          NaN                           NaN   \n",
       "1                          NaN                           NaN   \n",
       "2                          NaN                           NaN   \n",
       "3                          NaN                           NaN   \n",
       "4  Debt % of Consideration (%)  Stock % of Consideration (%)   \n",
       "\n",
       "           Unnamed: 37           Unnamed: 38 Unnamed: 39  \n",
       "0                  NaN                   NaN         NaN  \n",
       "1                  NaN                   NaN         NaN  \n",
       "2                  NaN                   NaN         NaN  \n",
       "3                  NaN                   NaN         NaN  \n",
       "4  Buyer's Headquarter  Seller's Headquarter        Beta  \n",
       "\n",
       "[5 rows x 40 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Import CapIQ data from a csv export\n",
    "\n",
    "df_raw = r'/Users/valentincatteau/Desktop/1. Education/0. ESSEC/0. Term 1/7. Research Methods in Finance/Final project/final/cap_iq_export.xlsx'\n",
    "df_raw = pd.read_excel(df_raw)\n",
    "\n",
    "df_raw.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b0ed309e-4a33-4fc4-ab23-051532eb8b30",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Drop first rows and rename columns\n",
    "\n",
    "df_raw = df_raw.iloc[6:].reset_index(drop=True)\n",
    "\n",
    "df_raw.columns = [\n",
    "    \"c_ticker\",\n",
    "    \"c_name\",\n",
    "    \"t_id\",\n",
    "    \"deal_size\",\n",
    "    \"target_type\",\n",
    "    \"nosh_m1\",\n",
    "    \"ebitda\",\n",
    "    \"ebitda_margin\",\n",
    "    \"assets_total\",\n",
    "    \"equity_book_value\",\n",
    "    \"cash\",\n",
    "    \"net_debt\",\n",
    "    \"industry\",\n",
    "    \"announced_date\",\n",
    "    \"share_price_d0\",\n",
    "    \"date_m1\",\n",
    "    \"share_price_m1\",\n",
    "    \"date_m2\",\n",
    "    \"share_price_m2\",\n",
    "    \"date_m3\",\n",
    "    \"share_price_m3\",\n",
    "    \"date_m4\",\n",
    "    \"share_price_m4\",\n",
    "    \"date_p1\",\n",
    "    \"share_price_p1\",\n",
    "    \"date_p2\",\n",
    "    \"share_price_p2\",\n",
    "    \"date_p3\",\n",
    "    \"share_price_p3\",\n",
    "    \"date_p4\",\n",
    "    \"share_price_p4\",\n",
    "    \"payment_method\",\n",
    "    \"cash_payment_total\",\n",
    "    \"cash_payment_pct\",\n",
    "    \"debt_payment_total\",\n",
    "    \"debt_payment_pct\",\n",
    "    \"stock_payment_pct\",\n",
    "    \"buyer_hq\",\n",
    "    \"target_hq\",\n",
    "    \"beta\"\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b91da752-0f6b-419a-a333-2a717a473251",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Convert variables to correct data type \n",
    "\n",
    "df_raw[\"announced_date\"] = df_raw[\"announced_date\"].astype(str).str[:-9]\n",
    "df_raw[\"date_m1\"] = df_raw[\"date_m1\"].astype(str).str[:-9]\n",
    "df_raw[\"date_m2\"] = df_raw[\"date_m2\"].astype(str).str[:-9]\n",
    "df_raw[\"date_m3\"] = df_raw[\"date_m3\"].astype(str).str[:-9]\n",
    "df_raw[\"date_m4\"] = df_raw[\"date_m4\"].astype(str).str[:-9]\n",
    "\n",
    "df_raw[\"date_p1\"] = df_raw[\"date_p1\"].astype(str).str[:-9]\n",
    "df_raw[\"date_p2\"] = df_raw[\"date_p2\"].astype(str).str[:-9]\n",
    "df_raw[\"date_p3\"] = df_raw[\"date_p3\"].astype(str).str[:-9]\n",
    "df_raw[\"date_p4\"] = df_raw[\"date_p4\"].astype(str).str[:-9]\n",
    "\n",
    "df_raw[\"announced_date\"] = pd.to_datetime(df_raw[\"announced_date\"], errors=\"coerce\")\n",
    "df_raw[\"date_m1\"] = pd.to_datetime(df_raw[\"date_m1\"], errors=\"coerce\")\n",
    "df_raw[\"date_m2\"] = pd.to_datetime(df_raw[\"date_m2\"], errors=\"coerce\")\n",
    "df_raw[\"date_m3\"] = pd.to_datetime(df_raw[\"date_m3\"], errors=\"coerce\")\n",
    "df_raw[\"date_m4\"] = pd.to_datetime(df_raw[\"date_m4\"], errors=\"coerce\")\n",
    "\n",
    "df_raw[\"date_p1\"] = pd.to_datetime(df_raw[\"date_p1\"], errors=\"coerce\")\n",
    "df_raw[\"date_p2\"] = pd.to_datetime(df_raw[\"date_p2\"], errors=\"coerce\")\n",
    "df_raw[\"date_p3\"] = pd.to_datetime(df_raw[\"date_p3\"], errors=\"coerce\")\n",
    "df_raw[\"date_p4\"] = pd.to_datetime(df_raw[\"date_p4\"], errors=\"coerce\")\n",
    "\n",
    "df_raw = df_raw.assign(**{\n",
    "    col: pd.to_numeric(df_raw[col], errors=\"coerce\")\n",
    "    for col in df_raw.columns\n",
    "    if col not in [\"c_ticker\", \"c_name\", \"t_id\", \"target_type\", \"industry\", \"announced_date\",\n",
    "                   \"date_m1\", \"date_m2\", \"date_m3\", \"date_m4\" \"date_p1\", \"date_p2\", \"date_p3\", \"date_p4\",\n",
    "                   \"payment_method\", \"buyer_hq\", \"target_hq\"]\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c66ffc74-a045-4a24-8815-976e0103ad5b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# create mcap and deal size/mcap variables\n",
    "\n",
    "df_raw[\"mcap_m1\"] = (df_raw[\"nosh_m1\"] * df_raw[\"share_price_m1\"])\n",
    "df_raw[\"deal_mcap\"] = (df_raw[\"deal_size\"] / df_raw[\"mcap_m1\"]) * 100\n",
    "df_raw[\"deal_mcap\"] = df_raw[\"deal_mcap\"].replace([np.inf, -np.inf], np.nan)\n",
    "df_raw = df_raw.dropna(subset=[\"deal_mcap\"])\n",
    "q99 = df_raw[\"deal_mcap\"].quantile(0.99)\n",
    "df_raw = df_raw[df_raw[\"deal_mcap\"] <= q99].copy()\n",
    "df_raw[\"deal_mcap\"] = df_raw[\"deal_mcap\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "fe820c1f-10a8-4ddd-bb11-8dbcda9ad88c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>c_ticker</th>\n",
       "      <th>c_name</th>\n",
       "      <th>t_id</th>\n",
       "      <th>deal_size</th>\n",
       "      <th>target_type</th>\n",
       "      <th>nosh_m1</th>\n",
       "      <th>ebitda</th>\n",
       "      <th>ebitda_margin</th>\n",
       "      <th>assets_total</th>\n",
       "      <th>equity_book_value</th>\n",
       "      <th>...</th>\n",
       "      <th>mcap_group</th>\n",
       "      <th>large_cap</th>\n",
       "      <th>mid_cap</th>\n",
       "      <th>small_cap</th>\n",
       "      <th>target_public</th>\n",
       "      <th>cross_border</th>\n",
       "      <th>debt_ebitda</th>\n",
       "      <th>cash_assets_ratio</th>\n",
       "      <th>pb_ratio</th>\n",
       "      <th>mcap_log</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>SEE</td>\n",
       "      <td>Seeing Machines Limited (AIM:SEE)</td>\n",
       "      <td>IQTR1887325548</td>\n",
       "      <td>6.000</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>145.61467</td>\n",
       "      <td>1056.20000</td>\n",
       "      <td>19.2424</td>\n",
       "      <td>7200.60000</td>\n",
       "      <td>7200.60000</td>\n",
       "      <td>...</td>\n",
       "      <td>large</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>420.384397</td>\n",
       "      <td>4.806544</td>\n",
       "      <td>68.311857</td>\n",
       "      <td>8.500833</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ESE</td>\n",
       "      <td>ESCO Technologies Inc. (NYSE:ESE)</td>\n",
       "      <td>IQTR1887383347</td>\n",
       "      <td>550.000</td>\n",
       "      <td>Assets/Products</td>\n",
       "      <td>25.75106</td>\n",
       "      <td>182.57300</td>\n",
       "      <td>18.8443</td>\n",
       "      <td>1772.52600</td>\n",
       "      <td>1772.52600</td>\n",
       "      <td>...</td>\n",
       "      <td>large</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>98.684362</td>\n",
       "      <td>2.899591</td>\n",
       "      <td>149.448388</td>\n",
       "      <td>7.881942</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>FQT</td>\n",
       "      <td>Frequentis AG (XTRA:FQT)</td>\n",
       "      <td>IQTR1887530302</td>\n",
       "      <td>0.575</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>13.26152</td>\n",
       "      <td>34.18813</td>\n",
       "      <td>7.1668</td>\n",
       "      <td>410.16027</td>\n",
       "      <td>410.16027</td>\n",
       "      <td>...</td>\n",
       "      <td>mid</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>-134.565155</td>\n",
       "      <td>19.990729</td>\n",
       "      <td>110.610367</td>\n",
       "      <td>6.117392</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>KEYS</td>\n",
       "      <td>Keysight Technologies, Inc. (NYSE:KEYS)</td>\n",
       "      <td>IQTR1887943481</td>\n",
       "      <td>117.000</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>174.53924</td>\n",
       "      <td>1591.00000</td>\n",
       "      <td>29.1178</td>\n",
       "      <td>8683.00000</td>\n",
       "      <td>8683.00000</td>\n",
       "      <td>...</td>\n",
       "      <td>large</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>-28.032684</td>\n",
       "      <td>28.469423</td>\n",
       "      <td>276.090805</td>\n",
       "      <td>10.084682</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>MKRO</td>\n",
       "      <td>Monkey Rock Group, Inc. (OTCPK:MKRO)</td>\n",
       "      <td>IQTR1888332653</td>\n",
       "      <td>0.271</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>371.50625</td>\n",
       "      <td>0.00000</td>\n",
       "      <td>0.0000</td>\n",
       "      <td>0.00000</td>\n",
       "      <td>0.00000</td>\n",
       "      <td>...</td>\n",
       "      <td>small</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>inf</td>\n",
       "      <td>NaN</td>\n",
       "      <td>inf</td>\n",
       "      <td>2.183689</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 52 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  c_ticker                                   c_name            t_id  \\\n",
       "0      SEE        Seeing Machines Limited (AIM:SEE)  IQTR1887325548   \n",
       "1      ESE        ESCO Technologies Inc. (NYSE:ESE)  IQTR1887383347   \n",
       "2      FQT                 Frequentis AG (XTRA:FQT)  IQTR1887530302   \n",
       "3     KEYS  Keysight Technologies, Inc. (NYSE:KEYS)  IQTR1887943481   \n",
       "4     MKRO     Monkey Rock Group, Inc. (OTCPK:MKRO)  IQTR1888332653   \n",
       "\n",
       "   deal_size      target_type    nosh_m1      ebitda  ebitda_margin  \\\n",
       "0      6.000  Private Company  145.61467  1056.20000        19.2424   \n",
       "1    550.000  Assets/Products   25.75106   182.57300        18.8443   \n",
       "2      0.575  Private Company   13.26152    34.18813         7.1668   \n",
       "3    117.000  Private Company  174.53924  1591.00000        29.1178   \n",
       "4      0.271  Private Company  371.50625     0.00000         0.0000   \n",
       "\n",
       "   assets_total  equity_book_value  ...  mcap_group  large_cap mid_cap  \\\n",
       "0    7200.60000         7200.60000  ...       large          1       0   \n",
       "1    1772.52600         1772.52600  ...       large          1       0   \n",
       "2     410.16027          410.16027  ...         mid          0       1   \n",
       "3    8683.00000         8683.00000  ...       large          1       0   \n",
       "4       0.00000            0.00000  ...       small          0       0   \n",
       "\n",
       "  small_cap  target_public cross_border  debt_ebitda cash_assets_ratio  \\\n",
       "0         0              0          1.0   420.384397          4.806544   \n",
       "1         0              0          1.0    98.684362          2.899591   \n",
       "2         0              0          0.0  -134.565155         19.990729   \n",
       "3         0              0          1.0   -28.032684         28.469423   \n",
       "4         1              0          1.0          inf               NaN   \n",
       "\n",
       "     pb_ratio   mcap_log  \n",
       "0   68.311857   8.500833  \n",
       "1  149.448388   7.881942  \n",
       "2  110.610367   6.117392  \n",
       "3  276.090805  10.084682  \n",
       "4         inf   2.183689  \n",
       "\n",
       "[5 rows x 52 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Create mcap subsamples\n",
    "\n",
    "df_raw = df_raw[df_raw[\"mcap_m1\"] > 0].copy() # drops mcap NA such as negative or =0 share prices\n",
    "df_raw[\"mcap_group\"] = pd.qcut(\n",
    "    df_raw[\"mcap_m1\"],\n",
    "    q=3,\n",
    "    labels=[\"small\", \"mid\", \"large\"]\n",
    ")\n",
    "df_raw[\"large_cap\"] = (df_raw[\"mcap_group\"] == \"large\").astype(int)\n",
    "df_raw[\"mid_cap\"]   = (df_raw[\"mcap_group\"] == \"mid\").astype(int)\n",
    "df_raw[\"small_cap\"] = (df_raw[\"mcap_group\"] == \"small\").astype(int)\n",
    "\n",
    "# create target type dummy for target where =1 if target is public\n",
    "\n",
    "df_raw[\"target_public\"] = (df_raw[\"target_type\"] == \"Public Company\").astype(int)\n",
    "\n",
    "# create cross-border dummy for deal where =1 if target HQ =/= buyer HQ\n",
    "\n",
    "df_raw[\"cross_border\"] = (df_raw[\"buyer_hq\"] != df_raw[\"target_hq\"]).astype(int)\n",
    "df_raw.loc[df_raw[\"buyer_hq\"].isna() | df_raw[\"target_hq\"].isna(), \"cross_border\"] = np.nan\n",
    "\n",
    "# compute new variables\n",
    "\n",
    "df_raw[\"debt_ebitda\"] = df_raw[\"net_debt\"] / df_raw[\"ebitda\"]    \n",
    "df_raw[\"cash_assets_ratio\"] = df_raw[\"cash\"] / df_raw[\"assets_total\"]\n",
    "df_raw[\"pb_ratio\"] = df_raw[\"mcap_m1\"] / df_raw[\"equity_book_value\"]\n",
    "\n",
    "# adjust scales\n",
    "\n",
    "df_raw[\"mcap_log\"] = np.log(df_raw[\"mcap_m1\"])\n",
    "df_raw[\"cash_assets_ratio\"] = df_raw[\"cash_assets_ratio\"] * 100\n",
    "df_raw[\"pb_ratio\"] = df_raw[\"pb_ratio\"] * 100\n",
    "df_raw[\"debt_ebitda\"] = df_raw[\"debt_ebitda\"] * 100\n",
    "\n",
    "df_raw.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "24e9ea5d-3f89-4f65-aec4-043ad778c742",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>stoxx_value</th>\n",
       "      <th>stoxx_return</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>170</td>\n",
       "      <td>170.000000</td>\n",
       "      <td>170.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>2024-04-03 07:37:24.705882368</td>\n",
       "      <td>500.457529</td>\n",
       "      <td>-0.005318</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>2023-12-01 00:00:00</td>\n",
       "      <td>465.780000</td>\n",
       "      <td>-1.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>2024-02-02 18:00:00</td>\n",
       "      <td>484.832500</td>\n",
       "      <td>-0.002634</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>2024-04-04 12:00:00</td>\n",
       "      <td>505.570000</td>\n",
       "      <td>0.000195</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>2024-06-03 18:00:00</td>\n",
       "      <td>514.805000</td>\n",
       "      <td>0.004576</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>2024-08-01 00:00:00</td>\n",
       "      <td>524.710000</td>\n",
       "      <td>0.011791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>NaN</td>\n",
       "      <td>17.277645</td>\n",
       "      <td>0.076941</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                date  stoxx_value  stoxx_return\n",
       "count                            170   170.000000    170.000000\n",
       "mean   2024-04-03 07:37:24.705882368   500.457529     -0.005318\n",
       "min              2023-12-01 00:00:00   465.780000     -1.000000\n",
       "25%              2024-02-02 18:00:00   484.832500     -0.002634\n",
       "50%              2024-04-04 12:00:00   505.570000      0.000195\n",
       "75%              2024-06-03 18:00:00   514.805000      0.004576\n",
       "max              2024-08-01 00:00:00   524.710000      0.011791\n",
       "std                              NaN    17.277645      0.076941"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Import STOXX 600 (benchmark index) daily returns \n",
    "\n",
    "index_returns = r'/Users/valentincatteau/Desktop/1. Education/0. ESSEC/0. Term 1/7. Research Methods in Finance/Final project/index_returns.xlsx'\n",
    "index_returns = pd.read_excel(index_returns)\n",
    "\n",
    "index_returns[\"stoxx_value\"] = pd.to_numeric(index_returns[\"stoxx_value\"], errors=\"coerce\")\n",
    "index_returns[\"stoxx_return\"] = pd.to_numeric(index_returns[\"stoxx_return\"], errors=\"coerce\")\n",
    "\n",
    "index_returns.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "619f8841-dd14-4567-a6ef-2796daaab13b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>c_ticker</th>\n",
       "      <th>c_name</th>\n",
       "      <th>t_id</th>\n",
       "      <th>deal_size</th>\n",
       "      <th>target_type</th>\n",
       "      <th>nosh_m1</th>\n",
       "      <th>ebitda</th>\n",
       "      <th>ebitda_margin</th>\n",
       "      <th>assets_total</th>\n",
       "      <th>equity_book_value</th>\n",
       "      <th>...</th>\n",
       "      <th>stoxx_value_p1</th>\n",
       "      <th>date_p2_</th>\n",
       "      <th>stoxx_return_p2</th>\n",
       "      <th>stoxx_value_p2</th>\n",
       "      <th>date_p3_</th>\n",
       "      <th>stoxx_return_p3</th>\n",
       "      <th>stoxx_value_p3</th>\n",
       "      <th>date_p4_</th>\n",
       "      <th>stoxx_return_p4</th>\n",
       "      <th>stoxx_value_p4</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>CWK</td>\n",
       "      <td>Cranswick plc (LSE:CWK)</td>\n",
       "      <td>IQTR1867871142</td>\n",
       "      <td>12.500</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>229.15802</td>\n",
       "      <td>429.60000</td>\n",
       "      <td>4.5251</td>\n",
       "      <td>7774.00000</td>\n",
       "      <td>7774.00000</td>\n",
       "      <td>...</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.192396</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ETTE</td>\n",
       "      <td>Etteplan Oyj (HLSE:ETTE)</td>\n",
       "      <td>IQTR1867780682</td>\n",
       "      <td>17.120</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>25.24987</td>\n",
       "      <td>38.15077</td>\n",
       "      <td>9.5888</td>\n",
       "      <td>314.59600</td>\n",
       "      <td>314.59600</td>\n",
       "      <td>...</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.192396</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>506734</td>\n",
       "      <td>Mysore Petro Chemicals Limited (BSE:506734)</td>\n",
       "      <td>IQTR1867824132</td>\n",
       "      <td>1.150</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>6.58349</td>\n",
       "      <td>-0.45005</td>\n",
       "      <td>-19.3786</td>\n",
       "      <td>0.00000</td>\n",
       "      <td>0.00000</td>\n",
       "      <td>...</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.192396</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>NORRH</td>\n",
       "      <td>Norrhydro Group Oyj (HLSE:NORRH)</td>\n",
       "      <td>IQTR1867790430</td>\n",
       "      <td>0.435</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>11.08612</td>\n",
       "      <td>0.77803</td>\n",
       "      <td>2.3180</td>\n",
       "      <td>28.03705</td>\n",
       "      <td>28.03705</td>\n",
       "      <td>...</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.192396</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>GAMA</td>\n",
       "      <td>Gamma Communications plc (LSE:GAMA)</td>\n",
       "      <td>IQTR1867785910</td>\n",
       "      <td>29.470</td>\n",
       "      <td>Private Company</td>\n",
       "      <td>96.88468</td>\n",
       "      <td>129.79569</td>\n",
       "      <td>19.5322</td>\n",
       "      <td>604.77913</td>\n",
       "      <td>604.77913</td>\n",
       "      <td>...</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.192396</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "      <td>2024-01-08</td>\n",
       "      <td>-0.001924</td>\n",
       "      <td>478.18</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 79 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  c_ticker                                       c_name            t_id  \\\n",
       "0      CWK                      Cranswick plc (LSE:CWK)  IQTR1867871142   \n",
       "1     ETTE                     Etteplan Oyj (HLSE:ETTE)  IQTR1867780682   \n",
       "2   506734  Mysore Petro Chemicals Limited (BSE:506734)  IQTR1867824132   \n",
       "3    NORRH             Norrhydro Group Oyj (HLSE:NORRH)  IQTR1867790430   \n",
       "4     GAMA          Gamma Communications plc (LSE:GAMA)  IQTR1867785910   \n",
       "\n",
       "   deal_size      target_type    nosh_m1     ebitda  ebitda_margin  \\\n",
       "0     12.500  Private Company  229.15802  429.60000         4.5251   \n",
       "1     17.120  Private Company   25.24987   38.15077         9.5888   \n",
       "2      1.150  Private Company    6.58349   -0.45005       -19.3786   \n",
       "3      0.435  Private Company   11.08612    0.77803         2.3180   \n",
       "4     29.470  Private Company   96.88468  129.79569        19.5322   \n",
       "\n",
       "   assets_total  equity_book_value  ...  stoxx_value_p1   date_p2_  \\\n",
       "0    7774.00000         7774.00000  ...          478.18 2024-01-08   \n",
       "1     314.59600          314.59600  ...          478.18 2024-01-08   \n",
       "2       0.00000            0.00000  ...          478.18 2024-01-08   \n",
       "3      28.03705           28.03705  ...          478.18 2024-01-08   \n",
       "4     604.77913          604.77913  ...          478.18 2024-01-08   \n",
       "\n",
       "  stoxx_return_p2 stoxx_value_p2   date_p3_ stoxx_return_p3  stoxx_value_p3  \\\n",
       "0       -0.192396         478.18 2024-01-08       -0.001924          478.18   \n",
       "1       -0.192396         478.18 2024-01-08       -0.001924          478.18   \n",
       "2       -0.192396         478.18 2024-01-08       -0.001924          478.18   \n",
       "3       -0.192396         478.18 2024-01-08       -0.001924          478.18   \n",
       "4       -0.192396         478.18 2024-01-08       -0.001924          478.18   \n",
       "\n",
       "    date_p4_  stoxx_return_p4 stoxx_value_p4  \n",
       "0 2024-01-08        -0.001924         478.18  \n",
       "1 2024-01-08        -0.001924         478.18  \n",
       "2 2024-01-08        -0.001924         478.18  \n",
       "3 2024-01-08        -0.001924         478.18  \n",
       "4 2024-01-08        -0.001924         478.18  \n",
       "\n",
       "[5 rows x 79 columns]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Merge STOXX 600 daily returns with main df\n",
    "# Let us match missing values for m7, m1, d1, d7: if day of the week is a week-end, take closest value)\n",
    "\n",
    "index_returns[\"date\"] = pd.to_datetime(index_returns[\"date\"])\n",
    "index_returns = index_returns.sort_values(\"date\")\n",
    "\n",
    "# Merge STOXX 600 returns on day of announcement\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"announced_date\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"announced_date\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"forward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_0_\",\n",
    "    \"stoxx_return\": \"stoxx_return_0\",\n",
    "    \"stoxx_value\": \"stoxx_value_0\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d-1\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_0_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_0_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"backward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_m1_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_m1\",\n",
    "    \"stoxx_value\": \"stoxx_value_m1\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d-2\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_m1_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_m1_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"backward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_m2_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_m2\",\n",
    "    \"stoxx_value\": \"stoxx_value_m2\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d-3\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_m2_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_m2_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"backward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_m3_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_m3\",\n",
    "    \"stoxx_value\": \"stoxx_value_m3\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d-4\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_m3_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_m3_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"backward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_m4_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_m4\",\n",
    "    \"stoxx_value\": \"stoxx_value_m4\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d+1\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_0_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_0_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"forward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_p1_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_p1\",\n",
    "    \"stoxx_value\": \"stoxx_value_p1\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d+2\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_p1_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_p1_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"forward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_p2_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_p2\",\n",
    "    \"stoxx_value\": \"stoxx_value_p2\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d+3\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_p2_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_p2_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"forward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_p3_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_p3\",\n",
    "    \"stoxx_value\": \"stoxx_value_p3\"\n",
    "})\n",
    "\n",
    "# Merge STOXX 600 returns on d+4\n",
    "\n",
    "df_raw = pd.merge_asof(\n",
    "    df_raw.sort_values(\"date_p3_\"),\n",
    "    index_returns[[\"date\", \"stoxx_return\", \"stoxx_value\"]],\n",
    "    left_on=\"date_p3_\",\n",
    "    right_on=\"date\",\n",
    "    direction=\"forward\"\n",
    ").rename(columns={\n",
    "    \"date\": \"date_p4_\",    \n",
    "    \"stoxx_return\": \"stoxx_return_p4\",\n",
    "    \"stoxx_value\": \"stoxx_value_p4\"\n",
    "})\n",
    "\n",
    "# adjust scales\n",
    "\n",
    "df_raw[\"stoxx_return_m2\"] = df_raw[\"stoxx_return_m2\"] * 100\n",
    "df_raw[\"stoxx_return_m1\"] = df_raw[\"stoxx_return_m1\"] * 100\n",
    "df_raw[\"stoxx_return_0\"] = df_raw[\"stoxx_return_0\"] * 100\n",
    "df_raw[\"stoxx_return_p1\"] = df_raw[\"stoxx_return_p1\"] * 100\n",
    "df_raw[\"stoxx_return_p2\"] = df_raw[\"stoxx_return_p2\"] * 100\n",
    "\n",
    "df_raw.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "96baf218-c6b9-4ae7-b92f-2e3285224515",
   "metadata": {},
   "outputs": [],
   "source": [
    "# compute daily return\n",
    "\n",
    "df_raw[\"ret_m2\"] = df_raw[\"share_price_m2\"] / df_raw[\"share_price_m3\"] - 1\n",
    "df_raw[\"ret_m1\"] = df_raw[\"share_price_m1\"] / df_raw[\"share_price_m2\"] - 1\n",
    "df_raw[\"ret_0\"]  = df_raw[\"share_price_d0\"] / df_raw[\"share_price_m1\"] - 1\n",
    "df_raw[\"ret_p1\"] = df_raw[\"share_price_p1\"] / df_raw[\"share_price_d0\"] - 1\n",
    "df_raw[\"ret_p2\"] = df_raw[\"share_price_p2\"] / df_raw[\"share_price_p1\"] - 1\n",
    "\n",
    "# compute abnormal return without stock beta\n",
    "df_raw[\"ar_m2\"] = df_raw[\"ret_m2\"] - df_raw[\"stoxx_return_m2\"]\n",
    "df_raw[\"ar_m1\"] = df_raw[\"ret_m1\"] - df_raw[\"stoxx_return_m1\"]\n",
    "df_raw[\"ar_0\"]  = df_raw[\"ret_0\"]  - df_raw[\"stoxx_return_0\"]\n",
    "df_raw[\"ar_p1\"] = df_raw[\"ret_p1\"] - df_raw[\"stoxx_return_p1\"]\n",
    "df_raw[\"ar_p2\"] = df_raw[\"ret_p2\"] - df_raw[\"stoxx_return_p2\"]\n",
    "\n",
    "# drop extreme beta values (database inconsistencies)\n",
    "\n",
    "q99 = df_raw[\"beta\"].quantile(0.99)\n",
    "df_raw = df_raw[df_raw[\"beta\"] <= q99].copy()\n",
    "\n",
    "# compute abnormal return using stock beta\n",
    "\n",
    "df_raw[\"ar_b_m2\"] = df_raw[\"ret_m2\"] - df_raw[\"beta\"] * df_raw[\"stoxx_return_m2\"]\n",
    "df_raw[\"ar_b_m1\"] = df_raw[\"ret_m1\"] - df_raw[\"beta\"] * df_raw[\"stoxx_return_m1\"]\n",
    "df_raw[\"ar_b_0\"]  = df_raw[\"ret_0\"]  - df_raw[\"beta\"] * df_raw[\"stoxx_return_0\"]\n",
    "df_raw[\"ar_b_p1\"] = df_raw[\"ret_p1\"] - df_raw[\"beta\"] * df_raw[\"stoxx_return_p1\"]\n",
    "df_raw[\"ar_b_p2\"] = df_raw[\"ret_p2\"] - df_raw[\"beta\"] * df_raw[\"stoxx_return_p2\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "abbd369f-9c72-492d-a7d8-8850e616509a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Compute CAR1 (Cumulative Abnormal Returns -1/+1 day of announcement), which will be our dependant variable in regressions\n",
    "\n",
    "df_raw = df_raw.replace([np.inf, -np.inf], np.nan)\n",
    "\n",
    "# using market return as expected return\n",
    "\n",
    "df_raw[\"car_1\"] = (df_raw[[\"ar_m1\", \"ar_0\", \"ar_p1\"]].sum(axis=1))\n",
    "\n",
    "# using beta * market return as expected return\n",
    "\n",
    "df_raw[\"car_1_beta_adjusted\"] = (df_raw[[\"ar_b_m1\", \"ar_b_0\", \"ar_b_p1\"]].sum(axis=1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f7547e66-b7d2-4a2d-9d29-efe00f89adf2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Compute CAR2 (-2/+2 days), which will be used for our robustness check\n",
    "\n",
    "# using market return as expected return\n",
    "\n",
    "df_raw[\"car_2\"] = (df_raw[[\"ar_m2\", \"ar_m1\", \"ar_0\", \"ar_p1\", \"ar_p2\"]].sum(axis=1))\n",
    "\n",
    "# using beta * market return as expected return\n",
    "\n",
    "df_raw[\"car_2_beta_adjusted\"] = (df_raw[[\"ar_b_m2\", \"ar_b_m1\", \"ar_b_0\", \"ar_b_p1\", \"ar_b_p2\"]].sum(axis=1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6368035e-67db-47e0-b647-2d30a0fd2f4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# final data cleaning\n",
    "\n",
    "# export full df\n",
    "\n",
    "df_raw.to_excel(\"/Users/valentincatteau/Desktop/1. Education/0. ESSEC/0. Term 1/7. Research Methods in Finance/Final project/final/export_full.xlsx\", index=False)\n",
    "\n",
    "# Set transaction ID as index, reorder columns, keep only useful variables and rename df_clean\n",
    "\n",
    "df_raw = df_raw.sort_values(\"t_id\").reset_index(drop=True)\n",
    "df_clean = df_raw[\n",
    "    [\n",
    "        't_id', 'c_ticker',  'c_name', 'industry', 'mcap_m1', 'mcap_log', 'mcap_group', 'large_cap','mid_cap', 'small_cap',\n",
    "        'ebitda_margin', 'debt_ebitda', 'cash_assets_ratio', 'pb_ratio',\n",
    "        'announced_date',  'target_public', 'cash_payment_pct', 'deal_mcap', 'cross_border',\n",
    "        'car_1', 'car_2', 'car_1_beta_adjusted', 'car_2_beta_adjusted'\n",
    "    ]\n",
    "]\n",
    "\n",
    "# export clean df\n",
    "\n",
    "df_clean.to_excel(\"/Users/valentincatteau/Desktop/1. Education/0. ESSEC/0. Term 1/7. Research Methods in Finance/Final project/final/export_clean.xlsx\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c9139475-ecd3-413b-aad7-cdd340f20f3b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_1   R-squared:                       0.023\n",
      "Model:                            OLS   Adj. R-squared:                  0.006\n",
      "Method:                 Least Squares   F-statistic:                     1.432\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):              0.201\n",
      "Time:                        01:03:49   Log-Likelihood:                -781.84\n",
      "No. Observations:                 355   AIC:                             1578.\n",
      "Df Residuals:                     348   BIC:                             1605.\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept           -0.3574      0.525     -0.681      0.496      -1.385       0.671\n",
      "cash_payment_pct     0.0028      0.006      0.483      0.629      -0.009       0.014\n",
      "deal_mcap           -0.0015      0.001     -1.712      0.087      -0.003       0.000\n",
      "cross_border         0.4760      0.278      1.711      0.087      -0.069       1.021\n",
      "mcap_log            -0.0283      0.076     -0.372      0.710      -0.177       0.121\n",
      "pb_ratio          8.229e-05      0.000      0.294      0.768      -0.000       0.001\n",
      "debt_ebitda      -6.606e-05      0.000     -0.444      0.657      -0.000       0.000\n",
      "==============================================================================\n",
      "Omnibus:                      372.998   Durbin-Watson:                   1.514\n",
      "Prob(Omnibus):                  0.000   Jarque-Bera (JB):            28562.515\n",
      "Skew:                           4.270   Prob(JB):                         0.00\n",
      "Kurtosis:                      46.105   Cond. No.                     5.16e+03\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 5.16e+03. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n"
     ]
    }
   ],
   "source": [
    "# Run regression with entire sample\n",
    "\n",
    "reg_car_1 = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_1 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_clean\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_1.summary())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "742293ac-a41f-42a2-8264-d1e21b99b5e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run main regressions with subsambles of small, mid and large caps\n",
    "# Create 3 market cap subsamples\n",
    "\n",
    "df_small = df_raw[df_raw[\"small_cap\"] == 1]\n",
    "df_mid   = df_raw[df_raw[\"mid_cap\"] == 1]\n",
    "df_large = df_raw[df_raw[\"large_cap\"] == 1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "6e84fdef-507a-4d0b-81c4-a5b4f40e5bd7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_1   R-squared:                       0.071\n",
      "Model:                            OLS   Adj. R-squared:                  0.012\n",
      "Method:                 Least Squares   F-statistic:                    0.5313\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):              0.783\n",
      "Time:                        01:03:49   Log-Likelihood:                -253.38\n",
      "No. Observations:                 102   AIC:                             520.8\n",
      "Df Residuals:                      95   BIC:                             539.1\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept           -0.5689      1.087     -0.523      0.601      -2.700       1.562\n",
      "cash_payment_pct     0.0104      0.011      0.987      0.323      -0.010       0.031\n",
      "deal_mcap           -0.0019      0.002     -1.153      0.249      -0.005       0.001\n",
      "cross_border         0.9214      0.714      1.291      0.197      -0.478       2.321\n",
      "mcap_log            -0.1397      0.304     -0.459      0.646      -0.736       0.457\n",
      "pb_ratio            -0.0012      0.003     -0.382      0.702      -0.007       0.005\n",
      "debt_ebitda         -0.0005      0.001     -0.757      0.449      -0.002       0.001\n",
      "==============================================================================\n",
      "Omnibus:                      152.178   Durbin-Watson:                   1.818\n",
      "Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7793.493\n",
      "Skew:                           5.321   Prob(JB):                         0.00\n",
      "Kurtosis:                      44.479   Cond. No.                     3.65e+03\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 3.65e+03. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n"
     ]
    }
   ],
   "source": [
    "# Run regression with Small caps subsample\n",
    "\n",
    "reg_car_1_small = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_1 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_small\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_1_small.summary())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "25c367bb-4bea-47eb-91b5-8bb81c03f431",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_1   R-squared:                       0.097\n",
      "Model:                            OLS   Adj. R-squared:                  0.053\n",
      "Method:                 Least Squares   F-statistic:                     11.10\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):           7.24e-10\n",
      "Time:                        01:03:50   Log-Likelihood:                -258.05\n",
      "No. Observations:                 130   AIC:                             530.1\n",
      "Df Residuals:                     123   BIC:                             550.2\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept           -0.8186      1.849     -0.443      0.658      -4.442       2.805\n",
      "cash_payment_pct    -0.0006      0.008     -0.072      0.942      -0.017       0.015\n",
      "deal_mcap           -0.0229      0.008     -2.932      0.003      -0.038      -0.008\n",
      "cross_border         0.5106      0.315      1.620      0.105      -0.107       1.128\n",
      "mcap_log             0.0711      0.301      0.236      0.813      -0.519       0.662\n",
      "pb_ratio             0.0012      0.000      3.408      0.001       0.001       0.002\n",
      "debt_ebitda       -2.64e-05      0.000     -0.121      0.903      -0.000       0.000\n",
      "==============================================================================\n",
      "Omnibus:                       68.189   Durbin-Watson:                   1.749\n",
      "Prob(Omnibus):                  0.000   Jarque-Bera (JB):              453.002\n",
      "Skew:                           1.664   Prob(JB):                     4.28e-99\n",
      "Kurtosis:                      11.518   Cond. No.                     1.52e+04\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 1.52e+04. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n"
     ]
    }
   ],
   "source": [
    "# Run regression with Mid caps subsample\n",
    "\n",
    "reg_car_1_mid = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_1 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_mid\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_1_mid.summary())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "144a6fd4-466e-41ff-81a0-290210a94c15",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_1   R-squared:                       0.036\n",
      "Model:                            OLS   Adj. R-squared:                 -0.013\n",
      "Method:                 Least Squares   F-statistic:                    0.7947\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):              0.576\n",
      "Time:                        01:03:51   Log-Likelihood:                -239.64\n",
      "No. Observations:                 123   AIC:                             493.3\n",
      "Df Residuals:                     116   BIC:                             513.0\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept            0.4189      1.677      0.250      0.803      -2.867       3.705\n",
      "cash_payment_pct    -0.0035      0.011     -0.328      0.743      -0.025       0.018\n",
      "deal_mcap            0.0039      0.013      0.294      0.769      -0.022       0.030\n",
      "cross_border         0.0959      0.390      0.246      0.806      -0.668       0.860\n",
      "mcap_log            -0.0320      0.145     -0.220      0.826      -0.317       0.253\n",
      "pb_ratio         -6.866e-05      0.000     -0.180      0.857      -0.001       0.001\n",
      "debt_ebitda          0.0009      0.000      1.853      0.064   -5.16e-05       0.002\n",
      "==============================================================================\n",
      "Omnibus:                        0.478   Durbin-Watson:                   1.404\n",
      "Prob(Omnibus):                  0.787   Jarque-Bera (JB):                0.621\n",
      "Skew:                           0.050   Prob(JB):                        0.733\n",
      "Kurtosis:                       2.666   Cond. No.                     5.24e+03\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 5.24e+03. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n"
     ]
    }
   ],
   "source": [
    "# Run regression with Large caps subsample\n",
    "\n",
    "reg_car_1_large = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_1 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_large\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_1_large.summary())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "ff1d9852-ed9d-4d52-bcd9-532bf562f324",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_2   R-squared:                       0.026\n",
      "Model:                            OLS   Adj. R-squared:                  0.009\n",
      "Method:                 Least Squares   F-statistic:                     1.695\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):              0.121\n",
      "Time:                        01:03:51   Log-Likelihood:                -899.87\n",
      "No. Observations:                 355   AIC:                             1814.\n",
      "Df Residuals:                     348   BIC:                             1841.\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept           -0.6729      0.844     -0.797      0.426      -2.328       0.982\n",
      "cash_payment_pct     0.0022      0.009      0.250      0.803      -0.015       0.020\n",
      "deal_mcap           -0.0022      0.001     -2.151      0.031      -0.004      -0.000\n",
      "cross_border         0.6470      0.368      1.760      0.078      -0.074       1.368\n",
      "mcap_log            -0.0030      0.091     -0.033      0.974      -0.181       0.175\n",
      "pb_ratio             0.0002      0.000      0.469      0.639      -0.001       0.001\n",
      "debt_ebitda       -6.18e-05      0.000     -0.328      0.743      -0.000       0.000\n",
      "==============================================================================\n",
      "Omnibus:                      143.360   Durbin-Watson:                   1.332\n",
      "Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1306.765\n",
      "Skew:                           1.428   Prob(JB):                    1.74e-284\n",
      "Kurtosis:                      11.955   Cond. No.                     5.16e+03\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 5.16e+03. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n",
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_2   R-squared:                       0.077\n",
      "Model:                            OLS   Adj. R-squared:                  0.019\n",
      "Method:                 Least Squares   F-statistic:                    0.6670\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):              0.676\n",
      "Time:                        01:03:51   Log-Likelihood:                -272.35\n",
      "No. Observations:                 102   AIC:                             558.7\n",
      "Df Residuals:                      95   BIC:                             577.1\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept           -1.1991      1.625     -0.738      0.461      -4.384       1.986\n",
      "cash_payment_pct     0.0124      0.014      0.910      0.363      -0.014       0.039\n",
      "deal_mcap           -0.0026      0.002     -1.500      0.134      -0.006       0.001\n",
      "cross_border         1.1025      0.831      1.327      0.184      -0.525       2.730\n",
      "mcap_log            -0.0808      0.371     -0.218      0.828      -0.808       0.646\n",
      "pb_ratio            -0.0014      0.004     -0.367      0.713      -0.009       0.006\n",
      "debt_ebitda         -0.0006      0.001     -0.660      0.509      -0.002       0.001\n",
      "==============================================================================\n",
      "Omnibus:                       88.851   Durbin-Watson:                   1.772\n",
      "Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1169.331\n",
      "Skew:                           2.629   Prob(JB):                    1.21e-254\n",
      "Kurtosis:                      18.732   Cond. No.                     3.65e+03\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 3.65e+03. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n",
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_2   R-squared:                       0.115\n",
      "Model:                            OLS   Adj. R-squared:                  0.072\n",
      "Method:                 Least Squares   F-statistic:                     12.73\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):           3.86e-11\n",
      "Time:                        01:03:51   Log-Likelihood:                -309.75\n",
      "No. Observations:                 130   AIC:                             633.5\n",
      "Df Residuals:                     123   BIC:                             653.6\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept           -0.4843      2.436     -0.199      0.842      -5.259       4.290\n",
      "cash_payment_pct    -0.0010      0.013     -0.071      0.943      -0.027       0.025\n",
      "deal_mcap           -0.0366      0.012     -3.102      0.002      -0.060      -0.013\n",
      "cross_border         0.7719      0.494      1.561      0.118      -0.197       1.741\n",
      "mcap_log            -0.0298      0.403     -0.074      0.941      -0.820       0.760\n",
      "pb_ratio             0.0022      0.001      4.135      0.000       0.001       0.003\n",
      "debt_ebitda      -3.931e-05      0.000     -0.109      0.913      -0.001       0.001\n",
      "==============================================================================\n",
      "Omnibus:                        6.872   Durbin-Watson:                   1.846\n",
      "Prob(Omnibus):                  0.032   Jarque-Bera (JB):                6.681\n",
      "Skew:                           0.441   Prob(JB):                       0.0354\n",
      "Kurtosis:                       3.674   Cond. No.                     1.52e+04\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 1.52e+04. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n",
      "                            OLS Regression Results                            \n",
      "==============================================================================\n",
      "Dep. Variable:                  car_2   R-squared:                       0.037\n",
      "Model:                            OLS   Adj. R-squared:                 -0.013\n",
      "Method:                 Least Squares   F-statistic:                    0.7918\n",
      "Date:                Tue, 30 Dec 2025   Prob (F-statistic):              0.578\n",
      "Time:                        01:03:51   Log-Likelihood:                -302.63\n",
      "No. Observations:                 123   AIC:                             619.3\n",
      "Df Residuals:                     116   BIC:                             638.9\n",
      "Df Model:                           6                                         \n",
      "Covariance Type:                  HC3                                         \n",
      "====================================================================================\n",
      "                       coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------------\n",
      "Intercept            0.7054      2.793      0.253      0.801      -4.769       6.180\n",
      "cash_payment_pct    -0.0062      0.018     -0.344      0.731      -0.041       0.029\n",
      "deal_mcap            0.0066      0.022      0.302      0.763      -0.036       0.050\n",
      "cross_border         0.1496      0.650      0.230      0.818      -1.124       1.424\n",
      "mcap_log            -0.0508      0.243     -0.209      0.834      -0.526       0.425\n",
      "pb_ratio            -0.0001      0.001     -0.186      0.852      -0.001       0.001\n",
      "debt_ebitda          0.0015      0.001      1.840      0.066   -9.72e-05       0.003\n",
      "==============================================================================\n",
      "Omnibus:                        0.474   Durbin-Watson:                   1.403\n",
      "Prob(Omnibus):                  0.789   Jarque-Bera (JB):                0.618\n",
      "Skew:                           0.048   Prob(JB):                        0.734\n",
      "Kurtosis:                       2.666   Cond. No.                     5.24e+03\n",
      "==============================================================================\n",
      "\n",
      "Notes:\n",
      "[1] Standard Errors are heteroscedasticity robust (HC3)\n",
      "[2] The condition number is large, 5.24e+03. This might indicate that there are\n",
      "strong multicollinearity or other numerical problems.\n"
     ]
    }
   ],
   "source": [
    "# Robustness checks\n",
    "\n",
    "# full sample\n",
    "\n",
    "reg_car_1 = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_2 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_clean\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_1.summary())\n",
    "\n",
    "\n",
    "# small\n",
    "\n",
    "reg_car_2_small = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_2 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_small\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_2_small.summary())\n",
    "\n",
    "# mid\n",
    "\n",
    "reg_car_2_mid = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_2 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_mid\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_2_mid.summary())\n",
    "\n",
    "#large \n",
    "\n",
    "reg_car_2_large = smf.ols(\n",
    "    formula=\"\"\"\n",
    "    car_2 ~ cash_payment_pct\n",
    "    + deal_mcap\n",
    "    + cross_border\n",
    "    + mcap_log\n",
    "    + pb_ratio\n",
    "    + debt_ebitda\n",
    "    \"\"\",\n",
    "    data=df_large\n",
    ").fit(cov_type=\"HC3\")\n",
    "\n",
    "print(reg_car_2_large.summary())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "1b930d78-fa04-48a1-892f-21606165abf8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-0.12662956619792987"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_small['car_1'].mean()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "6371bc45-8e61-4ca4-bc36-f63fa4941515",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-0.3968454353707739"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_small['car_1'].median()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "18a954d8-afa6-4a53-85db-5b87314cd78b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-0.11256257471908601"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_mid['car_1'].mean()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "4e4446a1-abf5-4def-9559-f6c3164bff40",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-0.07271082592832356"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_mid['car_1'].median()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "9b49ddce-6b42-4bf3-b067-112f90df1142",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-0.023097126019198194"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_large['car_1'].mean()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "bec843e3-c0bd-4805-8d86-d7dbc79fdf47",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-0.10024204362302391"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_large['car_1'].median()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f64018eb-f234-439f-98f3-45b8445a7673",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
